// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'src/parser_test.dart' as src_parser_test;
import 'src/process_test.dart' as src_process_test;
import 'src/trait_data_test.dart' as src_trait_data_test;
import 'src/trait_test.dart' as src_trait_test;

void main() {
  src_trait_test.main();
  src_parser_test.main();
  src_process_test.main();
  src_trait_data_test.main();
}
